[project]
name = "datagen"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "faker",
    "pydantic"
]

[project.optional-dependencies]
dev = [
    "coverage",
    "pytest",
    "ruff"
]

[project.scripts]
datagen = "datagen.main:main"

[tool.uv]
package = true
